package ch.epfl.bonus.scanner;

public enum TokenType {

	NUMBER, EQUAL, VAR, IDENTIFIER,
	// OPERATORS
	PLUS, MINUS, XOR, AND, OR,
	// LOGIC OPERATORS
	EQUAL_EQUAL, BANG_EQUAL, GREATER_OR_EQUAL, SMALLER_OR_EQUAL, GREATER, SMALLER,
	// LANGUAGE KEYWORDS
	L_PARENTHESIS, L_CURLY_BRACES, R_PARENTHESIS, R_CURLY_BRACES, IF, ELSE, COMMA, OUTPUT, RETURN, WHILE;

}
